/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.chinook.chinook_interface;
import java.sql.*;
/**
 *
 * @author Felicity Unathi Moyo
 */
public class ChinookDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChinookDialog.class.getName());

    /**
     * Creates new form ChinookDialog
     */
    public ChinookDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getGenres();
        getAlbums();
        getMediaTypes();
    }
    private void getGenres(){
        try{
        Connection con  =Database.getDBConnection();
        String query = "Select GenreId, Name from Genre";
        PreparedStatement smt= con.prepareStatement(query);
        ResultSet results = smt.executeQuery();
       GenreOptions.removeAllItems();
        
        while(results.next()){
            GenreOptions.addItem(results.getInt("GenreId") + " - " + results.getString("Name"));
        }
        
        }catch(Exception e){
            e.getMessage();
        }
    }
    private void getAlbums(){
        try{
        Connection con  =Database.getDBConnection();
        String query = "Select AlbumId, Title from Album";
        PreparedStatement smt= con.prepareStatement(query);
        ResultSet results = smt.executeQuery();
        AlbumOptions.removeAllItems();
        
        while(results.next()){
            AlbumOptions.addItem(results.getInt("AlbumId") + " - " + results.getString("Title"));
        }
        
        }catch(Exception e){
             e.getMessage();
        }
    }
    private void getMediaTypes(){
        try{
        Connection con  =Database.getDBConnection();
        String query = "Select MediaTypeId, Name from mediatype";
        PreparedStatement smt= con.prepareStatement(query);
        ResultSet results = smt.executeQuery();
       MediaTypeOptions.removeAllItems();
        
        while(results.next()){
            MediaTypeOptions.addItem(results.getInt("MediaTypeId") + " - " + results.getString("Name"));
        }
        
        }catch(Exception e){
             e.getMessage();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        GenreOptions = new javax.swing.JComboBox<>();
        AlbumOptions = new javax.swing.JComboBox<>();
        MediaTypeOptions = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setText("Album Name");

        GenreOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GenreOptions.addActionListener(this::GenreOptionsActionPerformed);

        AlbumOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AlbumOptions.addActionListener(this::AlbumOptionsActionPerformed);

        MediaTypeOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField2.setText("Composer");

        jTextField3.setText("Milliseconds");

        jTextField4.setText("Bytes ");

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenreOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MediaTypeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlbumOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(MediaTypeOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlbumOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenreOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenreOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenreOptionsActionPerformed

    private void AlbumOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbumOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlbumOptionsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        Connection con= Database.getDBConnection();

String query = "INSERT INTO Track (TrackId,Name, AlbumId, MediaTypeId, GenreId,Composer,Milliseconds,Bytes, UnitPrice) VALUES (?, ?, ?, ?, ?, ?,?,?,?)";

PreparedStatement smt = con.prepareStatement(query);

smt.setInt(1, Integer.parseInt(jTextField5.getText().trim()));
smt.setString(2, jTextField1.getText());

smt.setInt(3, Integer.parseInt(AlbumOptions.getSelectedItem().toString().split(" - ")[0]));
smt.setInt(4, Integer.parseInt(MediaTypeOptions.getSelectedItem().toString().split(" - ")[0]));
smt.setInt(5, Integer.parseInt(GenreOptions.getSelectedItem().toString().split(" - ")[0]));
smt.setString(6, jTextField2.getText());

smt.setInt(7, Integer.parseInt(jTextField3.getText().trim()));
smt.setInt(8, Integer.parseInt(jTextField4.getText().trim()));
smt.setDouble(9, 0.99); 

smt.executeUpdate();
       }catch(Exception e){
           e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChinookDialog dialog = new ChinookDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlbumOptions;
    private javax.swing.JComboBox<String> GenreOptions;
    private javax.swing.JComboBox<String> MediaTypeOptions;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
